### ISSUE TITLE
External data?

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsRNet#28]
Hey @muschellij2 , 

We would like to turn some of the more well-vetted "apps" into ANTsRNet functions (e.g., [brain extraction](https://github.com/ANTsXNet/BrainExtraction)).  However, these require the download of external data (e.g., a template and the model weights).  In the R context, what is standard practice?  Specifically, to where should these data be downloaded?  A temp directory or inst/extdata/?  Presumably it would be nice to download these data to a destination where they can be recycled for future function calls.  Thanks.

**Comment by muschellij2** [comment]
OK quick thoughts:

1.  We're trying to make things like CRAN policy as much as we can within reason, so that means examples don't write to the users home directory and write to a tempdir.  Implication: any function should provide an `outdir` option or something like that to point to where to download data, and in examples, this should use `tempdir`.
2. Defaults for `outdir` can use `system.package("extdata",package = "ANTsRNet")`, which allows do a check like:
```r
dl_file = function(fname =  "h5_filename.h5", outdir = NULL) {
  if (is.null(outdir)) {
    outdir = system.package("extdata", package = "ANTsRNet")
  }
  fname = file.path(outdir, fname)
  if (!file.exists(fname)) {
    # download code
  }
  return(file.exists(fname))
}
```
This comes from the [CRAN comment](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages)
> It should not be used for other data files needed by the package, and the convention has grown up to use directory inst/extdata for such files.
3.  I'm not sure about "Standard practice".  [CRAN states](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages):
> If your package is to be distributed, do consider the resource implications of large datasets for your users: they can make packages very slow to download and use up unwelcome amounts of storage space

which I agree with (unless that's the sole purpose of the package).  So I think the way you do it is the best practice we have really.

**Comment by ntustison** [comment]
Sounds good.  Thanks @muschellij2 .  I'll be working on this relatively soon.

**Comment by muschellij2** [comment]
Relevant:
https://thecoatlessprofessor.com/programming/r/r-data-packages-in-external-data-repositories-using-the-additional_repositories-field/
Best,
John
