### ISSUE TITLE
Training with template base data augmentation

### ISSUE THREAD

**Issue by valeryozenne** [ANTsX/ANTsRNet#45]
Dear ANTs expert.

I'm not reporting a bug , I have basic question regarding the usage of antsRnet. 

## Objectives

I wish to perform segmentation using antsRnet. I have a small database of mouse brain in nifti format with the corresponding masks and I would like to test the template base data augmentation strategy. So far I've been able to :

- install antsR, antsPy, antsRnet, ansPynet on Ubuntu 20.04, and cuda and cudnn are happy.
- check that keras is working on my computer from Python and from R independlty of ANTs with typical example coming from the official documentation
- use different examples from the depreciated repository ANTsXNet
- BrainExtraction example (extraction) is working using the Python and R
- PigLungSegmentation example (extraction) is working using the Python and R  
- ProtonMRILungSegmentation (extraction) is working using the Python and R  
- BrainExtraction is working in Python with multiple MPRAGE data coming from our 3T Prisma, (result are really really good in 98% of the brain and completely wrong for the remaining 2%, I need to open later an another issue on this topics) 

- the mouse data are available in 3 matrix size in 32x32x32 , 64x64x64 , 128x128x128, only one is used   
- creation of the template for each using ANTs in bash was also fine and I get all usual transformations  

## Case 1:

- I try to use the training script from https://github.com/ANTsXNet/PigLungSegmentation/blob/master/Scripts/Training/trainUnetModel.R (I should have use the script from BrainExtraction but this one was slightly simpler).

- the script_training.R (enclosed) runs until the fit. All images, masks and transformation are correctly loaded.
- the error (Log1.txt enclosed) is the following : ValueError: Failed to find data adapter that can handle input: <class 'NoneType'>, <class 'NoneType'>, 

## Case 2: 

so I tried to look to another training example from ProtonMRILungSegmentation

-  I found that small adjustment was necessary regarding the depreciated example when creating the model, for instance the loss function must be defined in the script 

```
metric_multilabel_dice_coefficient <-
  custom_metric( "multilabel_dice_coefficient",
                 multilabel_dice_coefficient )

loss_dice <- function( y_true, y_pred ) {
  -multilabel_dice_coefficient(y_true, y_pred)
}
attr(loss_dice, "py_function_name") <- "multilabel_dice_coefficient"
```

- nevertheless the model crash during the fit (see Log2.txt)

## Case 3: 

I tried to test the simplest example I could find and I pick an example from the documentation https://github.com/ANTsX/ANTsRNet/blob/master/docs/reference/createUnetModel2D.html

```
library( ANTsR )
library( ANTsRNet )
library( keras )
keras::backend()$clear_session()
Sys.setenv( "CUDA_VISIBLE_DEVICES" = 1 )

imageIDs <- c( "r16", "r27", "r30", "r62", "r64", "r85" )
trainingBatchSize <- length( imageIDs )

# Perform simple 3-tissue segmentation.

segmentationLabels <- c( 1, 2, 3 )
numberOfLabels <- length( segmentationLabels )
initialization <- paste0( 'KMeans[', numberOfLabels, ']' )

domainImage <- antsImageRead( getANTsRData( imageIDs[1] ) )

X_train <- array( data = NA, dim = c( trainingBatchSize, dim( domainImage ), 1 ) )
Y_train <- array( data = NA, dim = c( trainingBatchSize, dim( domainImage ) ) )

images <- list()
segmentations <- list()

for( i in seq_len( trainingBatchSize ) )
{
  cat( "Processing image", imageIDs[i], "\n" )
  image <- antsImageRead( getANTsRData( imageIDs[i] ) )
  mask <- getMask( image )
  segmentation <- atropos( image, mask, initialization )$segmentation
  
  X_train[i,,, 1] <- as.array( image )
  Y_train[i,,] <- as.array( segmentation )
}
#> Processing image r16 
#> Processing image r27 
#> Processing image r30 
#> Processing image r62 
#> Processing image r64 
#> Processing image r85 
Y_train <- encodeUnet( Y_train, segmentationLabels )

# Perform a simple normalization

X_train <- ( X_train - mean( X_train ) ) / sd( X_train )

# Create the model

model <- createUnetModel2D( c( dim( domainImage ), 1 ),
                            numberOfOutputs = numberOfLabels )

metric_multilabel_dice_coefficient <-
  custom_metric( "multilabel_dice_coefficient",
                 multilabel_dice_coefficient )

loss_dice <- function( y_true, y_pred ) {
  -multilabel_dice_coefficient(y_true, y_pred)
}
attr(loss_dice, "py_function_name") <- "multilabel_dice_coefficient"

model %>% compile( loss = loss_dice,
                   optimizer = optimizer_adam( lr = 0.0001 ),
                   metrics = metric_multilabel_dice_coefficient )

# Comment out the rest due to travis build constraints

# Fit the model


print(model)
summary(model)


print(dim(X_train))
print(dim(Y_train))

track <- model %>% fit( X_train, Y_train,
              epochs = 100, batch_size = 5, verbose = 1, shuffle = TRUE,
              callbacks = list(
                callback_model_checkpoint( "unetModelInterimWeights.h5",
                    monitor = 'val_loss', save_best_only = TRUE ),
                callback_reduce_lr_on_plateau( monitor = "val_loss", factor = 0.1 )
              ),
              validation_split = 0.2 )

```

- Again the code crash during the fit (see log3.txt enclosed). The script is also enclosed

## Disclaim

 - R and Keras are mostly new to me. 

## Questions:

I wish first to solve the simplest example related to case 3. 

- Question a) is the issue related to keras or to antsRnet or to a mistake in the script ?
- Question b) what would be the best way to debug such error ? I wish to debug this kind of issue myself but I'm  lost by the error messages until now.  
- Question c) My GPU have only 4Go but I don't think that an issue , could you confirm ?
- Question d) For all cases. If the definition of the model or the loss evaluation doesn't match the dimension of my data, I'm expected that the error message will be more explicit, is it true ?
- Question e) Is there any other test/script I could launch to check my installation or usage of antsRnet.

Thanks in advance for your help.
Valéry 

## Script

[case_1_trainUnetModel.R.txt](https://github.com/ANTsX/ANTsRNet/files/6736483/case_1_trainUnetModel.R.txt)
[case_2_trainUnetModel_Valery.R.txt](https://github.com/ANTsX/ANTsRNet/files/6736487/case_2_trainUnetModel_Valery.R.txt)
[case_3_example_ants_createUnetModel2D.R.txt](https://github.com/ANTsX/ANTsRNet/files/6736488/case_3_example_ants_createUnetModel2D.R.txt)

## Log

[Log1.txt](https://github.com/ANTsX/ANTsRNet/files/6736489/Log1.txt)
[Log2.txt](https://github.com/ANTsX/ANTsRNet/files/6736490/Log2.txt)
[Log3.txt](https://github.com/ANTsX/ANTsRNet/files/6736491/Log3.txt)

**Comment by ntustison** [comment]
Hi @valeryozenne ,

It's great that you've had some success using ANTsRNet and ANTsPyNet.  You'll have to let us know more of your experience when you get a chance.  But first to this issue.  Before getting to your questions, though, let me clarify a couple things:

* I'm not so much a proponent of the *practical* utility of the template-based data augmentation approach anymore.  It's just too cumbersome to create and store the requisite warp files, particularly for 3-D data.  Rather, I tend to use [``randomlyTransformImageData``](https://github.com/ANTsX/ANTsRNet/blob/master/R/randomlyTransformImageData.R) or its Python [analog](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/randomly_transform_image_data.py).  Other data augmentation programs include:
    
    * ``ANTsRNet::histogramWarpImageIntensities.R``
    *  ``ANTsRNet::simulateBiasField``
    *  ``ANTsR::addNoiseToImage``

and their corresponding Python analogs.

* The example that you use for Case 3 could possibly be incorrect.  I haven't looked at those examples for awhile.  The problem is that the tensorflow and keras APIs have changed so much that it's quite possible we haven't updated everything accordingly.  Similarly, the deprecated code that you found in our ANTsXNet repo probably also suffers from outdated syntax.  If you're looking for a clean, up-to-date example, please look at this [repository](https://github.com/ntustison/Histograms/tree/main/ElBichoTraining) which corresponds to [this paper](https://www.medrxiv.org/content/10.1101/2021.03.04.21252588v5) which was just accepted for publication.  Specifically, you'll find examples for training in both Python and R in [this subdirectory](https://github.com/ntustison/Histograms/tree/main/ElBichoTraining).   The reason both Python and R examples exist is that even though I'm much more proficient in R, it seemed that there was a much larger memory overhead for R causing me to switch to Python for training. 

* So instead of trying to start with the old files you've found, let's start with some of the more recent training scripts.  I actually have a number of them that I'm more than willing to share.  It's just that I haven't quite figured out a place to post them.  Can you describe your data a bit more?  Do you just want to train a 3-D mouse brain extraction model using a simple foreground/background label set?  Also, how many subjects do you have?  Based on your answers, I have some recommendations that I can provide.

Nick

**Comment by valeryozenne** [comment]
Hi Nick,

Thanks for your prompt answer and advice

- About the template-based data augmentation, I will have a look to functions you mentioned. 

- Thanks for the new example with the Xenon acquisition. I will test the training scripts. Could you confirm that the corresponding datasets for training are available in this folder  https://github.com/ntustison/Histograms/tree/main/Analysis/Data/He2019_Dataverse/Nifti , and include a mask and ventilation with different simulated level of noise ? I haven't yet read the paper, I need to do it first. 
 
- My initial objectives are really simple. I want to train a 3-D mouse brain extraction model using a simple foreground/background label set. For long term, the objective to a have a robust solution to perform brain extraction in roden brain whatever the MRI contrast. So, this is not new, this topics has already been covered and some other solutions are already available in the literature but I wish to keep things consistent so I prefer to try to use the antsNet scripts. I also know that preprocessing step and data augmentation is important.

The goal is to have a tool that could be used in routine whatever the sequence (at least with 2 or 3 contrasts) in a similar way to the BrainExtraction script in R you deliver for the clinical data. As a first a test, we applied directly the brainExtraction script on rodent data and the result was not so bad  (see image enclosed) but obviously some training must be performed. 

![mouse](https://user-images.githubusercontent.com/7050315/123942326-512d1780-d99b-11eb-86dd-4177f1654cb9.png)

A significant amount of data is available (> 100 but I don't have the exact number) but the number are reasonably low in comparison to the clinical activity. The initial number of subjects is 16 but increasing the database is not an issue once the script are running.       

I'm currently working with Lara, a master student in the lab, she knows Keras and she is currently playing with 3DUnet and also with ANTs. 

We will first read your last paper and have a look at the code. If you have uptodate training script for single-label or multi-label segmentation, we will be happy to test them. 

Thanks in advance,  
Valéry

**Comment by ntustison** [comment]
> Could you confirm that the corresponding datasets for training are available in this folder 

No, that's not the training data.  Unfortunately, I don't own the training data so I can't share it.

> A significant amount of data is available (> 100 

I suspect this should be enough with sufficient data augmentation using the functions I mentioned.

We recently retrained our T1-w human brain extraction and got much better results so I would look at the attached training example.  One thing to notice is the use of a sigmoid activation coupled with the binary loss doss coefficient (since there's a single foreground label) instead of softmax with multilabel dice.

[train_model.py.txt](https://github.com/ANTsX/ANTsRNet/files/6742103/train_model.py.txt)
[batch_generator.py.txt](https://github.com/ANTsX/ANTsRNet/files/6742105/batch_generator.py.txt)

**Comment by valeryozenne** [comment]
Thanks a lot for the scripts. That's really helpful. The training and prediction scripts are now working well on our data. I need to work a bit on my own on the data augmentation strategy you suggested and also on the database size but the first prediction using a another database find the web with a similar sequence is acceptable.

![Capture d’écran de 2021-07-09 14-01-37](https://user-images.githubusercontent.com/7050315/125075236-9dc0d300-e0be-11eb-9298-2dd05a44dc52.png)

I might have other questions in the future, I let you know. 
I close this issue
Best,

**Comment by ntustison** [comment]
Glad it worked.  And if you're interested, we could always incorporate any contributions back in the current set of trained models.
