### ISSUE TITLE
Reference for DeepFlash

### ISSUE THREAD

**Issue by thomshaw92** [ANTsX/ANTsRNet#51]
Hi,
Is there a reference for the DeepFlash hippocampal segmentation tool? Paper/ conference abstract?

Some feedback: it works really well, even at 7T! Thanks for the tool. :D

**Comment by ntustison** [comment]
@thomshaw92, thanks for the feedback.  I don't think I've personally tested it at 7T so it's good to hear it might be potentially generalizable.  Make sure that you've updated to the latest which includes an alternative preprocessing scheme using rank intensity to mitigate site effects.

Short answer:  Sorry, but no---no conference paper or otherwise.  

Longer answer:  DeepFlash has been a longtime collaborative effort with Mike Yassa (and lab) which predates ANTsXNet.  It's only recently (within the past couple months) that all the pieces came together to produce a decent tool.  Writing it up and posting it to biorxiv is at the top of my to-do list given that Mike and others are already sending data through this pipeline.  In the short term, though, If you need a reference for your own work or would like some relative performance indicators, I'd be more than willing to continue a private discussion.
