### ISSUE TITLE
How to install ANTsRNet

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsRNet#67]
Are there any installation instructions?

**Comment by ntustison** [comment]
Have you never used ANTsRNet before?  If not, then I can do it.  But I can also walk you through it if you want to do it.  Whatever you prefer.  Although it might be helpful if somebody else knows about this package.  Other than Brian, the only people I know who use ANTsRNet is Taki and Kristin's group at UPenn.

**Comment by ntustison** [comment]
But, basically, it's much easier now than it used to be.  ``keras::install_keras()`` does it all for you.

**Comment by cookpa** [comment]
Oh neat - it would be great to document this. If it's easy, might attract more users.

**Comment by ntustison** [comment]
Great.  

And note that I keep everything coordinated between the two packages which should be apparent when looking at the tutorials.  There might be one or two architectures that are in ANTsRNet that aren't in ANTsPyNet but this is simply because I started with the former.  And those architectures are not used in anything and I didn't consider it worth it to port over.  But other than that, everything is directly coordinated.

**Comment by cookpa** [comment]
Success! 

R:

```
install.packages("keras")
library(keras)
keras::install_keras()
```

Then bash:

```
git clone https://github.com/stnava/ITKR.git
git clone https://github.com/ANTsX/ANTsRCore.git
git clone https://github.com/ANTsX/ANTsR.git
R CMD INSTALL ITKR 
R CMD INSTALL ANTsRCore
R CMD INSTALL ANTsR
R CMD INSTALL ANTsRNet
```

Worked for me (Intel Mac, OS 14, R 4.3.1).
